_target_: src.models.gpd.lightning_trainer.LightningTrainer
_convert_: "all"

window_T: 100
batch_size: ${data_loader.params.batch_size}
max_agent_num: 33
strict_loading: True  
pred_window_T: 100  #　ａutoregressive prediction window size