_target_: src.models.planning_task.planning_lightning_trainer.PlanningLightningTrainer
_convert_: "all"

window_T: 21
batch_size: ${data_loader.params.batch_size}
max_agent_num: 33
strict_loading: False   # load ckpt时的strict参数
pred_window_T: 80